GET  http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1dWlkIjoiNDBlOTdmZDEtMjg3YS00NjAwLTg5NzItYmQ1MTM5NWViMTE0IiwibmFtZSI6IkFuZ2dhIDIiLCJlbWFpbCI6ImFuZ2dhMkBnbWFpbC5jb20iLCJpYXQiOjE2Njk0MDI3MjAsImV4cCI6MTY2OTQwMjc0MH0.CUfTMu3Kt17nOOAbNunAyptSdRXNY2Ne5w_9fAENl0o
###
GET  http://localhost:5000/users/5c8eabd0-5a3a-4c2e-999a-a5079ceec804
###
POST http://localhost:5000/users
Content-Type: application/json

{  
    "name": "Angga nugraha",
    "email": "angga@gmail.com",
    "password": "1234567",
    "confPassword": "1234567"
}
###
PATCH  http://localhost:5000/users/536fc3d5-f3d2-4def-9611-f65f3574f1a6
Content-Type: application/json

{  
    "name": "Angga updated",
    "email": "angga2@gmail.com",
    "password": "",
    "confPassword": ""
}
###
DELETE   http://localhost:5000/users/536fc3d5-f3d2-4def-9611-f65f3574f1a6
# Content-Type: application/json

# {  
#     "name": "abdul",
#     "email": "abdul@gmail.com",
#     "password": "",
#     "confPassword": "",
# }
###
GET http://localhost:5000/product?search_query=Bajigur
###
DELETE http://localhost:5000/logout

###
POST http://localhost:5000/login
Content-Type: application/json

{
    "email": "hilman@gmail.com",
    "password": "1234567"
}

###
GET  http://localhost:5000/token

###
GET  http://localhost:5000/me
###
GET  http://localhost:5000/product